import type { EmployerCostBreakdown, SalaryBreakdown } from 'maroctax';

export interface PayslipPdfInput {
  monthLabel: string;
  employeeLabel: string;
  gross: number;
  dependents: number;
  breakdown: SalaryBreakdown;
  employer: EmployerCostBreakdown;
}

function money(n: number): string {
  return `${n.toFixed(2)} MAD`;
}

export async function downloadPayslipPdf(input: PayslipPdfInput): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });

  const marginX = 48;
  let y = 56;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('maroctax — Payslip (estimate)', marginX, y);

  y += 20;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`Month: ${input.monthLabel}`, marginX, y);
  y += 16;
  doc.text(`Employee: ${input.employeeLabel}`, marginX, y);
  y += 16;
  doc.text(`Gross: ${money(input.gross)} · Dependents: ${input.dependents}`, marginX, y);

  y += 24;
  doc.setFont('helvetica', 'bold');
  doc.text('Employee breakdown', marginX, y);
  y += 14;
  doc.setFont('helvetica', 'normal');

  const rows: Array<[string, string]> = [
    ['CNSS (employee)', `- ${money(input.breakdown.cnss)}`],
    ['AMO (employee)', `- ${money(input.breakdown.amo)}`],
    ['Frais professionnels', `- ${money(input.breakdown.fraisProfessionnels)}`],
    ['IR', `- ${money(input.breakdown.ir)}`],
    ['Net salary', money(input.breakdown.net)],
  ];

  rows.forEach(([k, v]) => {
    doc.text(k, marginX, y);
    doc.text(v, marginX + 340, y, { align: 'right' });
    y += 16;
  });

  y += 12;
  doc.setFont('helvetica', 'bold');
  doc.text('Employer cost', marginX, y);
  y += 14;
  doc.setFont('helvetica', 'normal');

  const erows: Array<[string, string]> = [
    ['CNSS (employer)', money(input.employer.employerCnss)],
    ['Accident du travail', money(input.employer.employerCnssAccident)],
    ['AMO (employer)', money(input.employer.employerAmo)],
    ['Training tax', money(input.employer.employerTraining)],
    ['Total employer cost', money(input.employer.totalCost)],
  ];

  erows.forEach(([k, v]) => {
    doc.text(k, marginX, y);
    doc.text(v, marginX + 340, y, { align: 'right' });
    y += 16;
  });

  y = 760;
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(
    'Disclaimer: This PDF is an estimate generated by maroctax (open-source). Not an official government document.',
    marginX,
    y,
    { maxWidth: 500 },
  );

  const safeName = input.employeeLabel.trim() ? input.employeeLabel.trim() : 'employee';
  doc.save(`payslip_${safeName.replaceAll(' ', '_')}_${input.monthLabel}.pdf`);
}

